[ClassVersion("1.1.0"), FriendlyName("HostsFile")] 
class HostsFile : OMI_BaseResource
{
  [Key] string hostName;
  [Key] string ipAddress;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};


